#!/usr/bin/env bash
#
# Arquivo: sf-nestjs
# Descrição: NestJS Scaffolding
#
# Mais um script feito com ❤️ por: 
# - "Lucas Saliés Brum" <lucas@archlinux.com.br>
# 
# Criado em: 08/01/2023 20:42:12
# Atualizado: 08/01/2023 20:42:12

[ $1 ] && PROJECT="$1" || PROJECT="nestjs"
BROWSER="firefox"
LAUNCH="true"
TMUX_SESSION="Nest"

[ ! -d $PROJECT ] && nest new $PROJECT

cd $PROJECT

test -d .vscode || mkdir .vscode
test -d .github/workflows || mkdir -p .github/workflows

# .gitignore
test -f .gitignore || \
    curl -sLo .gitignore \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/common/gitignore/nestjs

# VSCode Settings
test -f .vscode/settings.json || \
    curl -sLo .vscode/settings.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/nestjs/settings.json

# VSCode Recommendations
test -f .vscode/extensions.json || \
    curl -sLo .vscode/extensions.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/nestjs/extensions.json

# VSCode Tasks
test -f .vscode/tasks.json || \
    curl -sLo .vscode/tasks.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/nestjs/tasks.json

# Github Workflows
test -f .github/workflows/nest.yml || \
    curl -sLo .github/workflows/nest.yml \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/common/gh-actions/nest.yml

pnpm install 1> /dev/null

if [ "$LAUNCH" == "true" ]; then
    \tmux has-session -t $TMUX_SESSION
    [ $? != 0 ] && \tmux kill-session -t $TMUX_SESSION
    \tmux new-session -d -s $TMUX_SESSION 2> /dev/null
    \tmux new-window -t $TMUX_SESSION -n pnpm -d
    \tmux send-keys -t $TMUX_SESSION:pnpm "cd $PROJECT ; pnpm run start:dev" ENTER
    \tmux detach -s $TMUX_SESSION
fi

[ "$LAUNCH" == "true" ] && $BROWSER http://localhost:3000