#!/usr/bin/env bash
#
# Arquivo: sf-laravel-vite
# Descrição: Scaffolding de um projeto usando o Laravel & Vite.js
#
# Mais um script feito com 💙 por "Lucas Saliés Brum" <lucas@archlinux.com.br>
# Demo: https://www.gettr.com/post/pgjgwb394b
# 
# Criado em: 23/09/2021 01:33:12
# Atualizado: 05/05/2022 13:03:04
#
# Referência de cores:
# FG: reset = 0, black = 30, red = 31, green = 32, yellow = 33, blue = 34, magenta = 35, cyan = 36, white = 37
# BG: reset = 0, black = 40, red = 41, green = 42, yellow = 43, blue = 44, magenta = 45, cyan = 46, white=47

command -v pnpm &> /dev/null || (echo -e "O programa \e[1;31mpnpm\e[0m não está instalado, instale-o primeiro." && exit)
command -v composer &> /dev/null || (echo -e "O programa \e[1;31mcomposer\e[0m não está instalado, instale-o primeiro." && exit)

[ $1 ] && PROJECT="$1" || PROJECT="laravel"
LAUNCH="false"
UPGRADE="true"
TMUX_SESSION="LIVV"
EDITOR="code"
BROWSER="firefox"


version() {
    echo "$(basename $0) v0.1b"
    exit 0
}

help() {
    echo "Uso: $(basename $0) -p nomedoprojeto [-l|-nl] [-u|-nu] -h -v"
    exit 0
}

upgrade() {
    echo -e "[\e[1;35m*\e[0m] Upgrading Composer..."
    sudo composer self-update --no-interaction --quiet 2> /dev/null
    echo -e "[\e[1;35m*\e[0m] Upgrading Larave Installer..."
    sudo composer global require laravel/installer --no-interaction --quiet 2> /dev/null
    echo -e "[\e[1;35m*\e[0m] Upgrading pnpm..."
    sudo pnpm add -g pnpm 1> /dev/null 2> /dev/null
}

launch() {
    \tmux has-session -t $TMUX_SESSION 2>/dev/null
    if [ $? != 0 ]; then
        \tmux kill-session -t $TMUX_SESSION
    fi

    \tmux new-session -d -s $TMUX_SESSION 2>/dev/null
    
    \tmux new-window -t $TMUX_SESSION -n artisan 
    \tmux new-window -t $TMUX_SESSION -n npm 

    \tmux send-keys -t $TMUX_SESSION:artisan "php artisan serve" ENTER
    \tmux send-keys -t $TMUX_SESSION:npm "pnpm run dev" ENTER

    \tmux detach -s $TMUX_SESSION

    $BROWSER http://localhost:8000
}

existent() {
    cd $PROJECT

    test -d database || mkdir database
    test -f database/database.sqlite || touch database/database.sqlite
    test -d .vscode || /usr/bin/mkdir .vscode
    test -d .github/workflows || /usr/bin/mkdir -p .github/workflows

    echo -e "[\e[1;35m*\e[0m] Installing settings.json..."
    test -f .vscode/settings.json || \
        curl -sL -o .vscode/settings.json \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/settings.json
    
    echo -e "[\e[1;35m*\e[0m] Installing tasks.json..."
    test -f .vscode/tasks.json || \
        curl -sL -o .vscode/tasks.json \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/tasks.json

    echo -e "[\e[1;35m*\e[0m] Installing livv.yml..."
    test -f .github/workflows/livv.yml || \
        curl -sL -o .github/workflows/livv.yml \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/livv.yml    

    echo -e "[\e[1;35m*\e[0m] Installing .prettierrc.json..."
    test -f .prettierrc.json || \
        curl -sL -o .prettierrc.json \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/.prettierrc.json

    echo -e "[\e[1;35m*\e[0m] Installing .env..."
    test -f .env || \
        curl -sL -o .env \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/.env

    echo -e "[\e[1;35m*\e[0m] Installing .env.example..."
    test -f .env.example || \
        curl -sL -o .env.example \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/.env.example

    echo -e "[\e[1;35m*\e[0m] Installing ansible.sh..."
    test -f ansible.sh || \
        curl -sL -o ansible.sh \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/ansible.sh

    echo -e "[\e[1;35m*\e[0m] Installing ansible.yml..."
    test -f ansible.yml || \
        curl -sL -o ansible.yml \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/ansible.yml

    echo -e "[\e[1;35m*\e[0m] Installing livv.sh..."
    test -f livv.sh || \
        curl -sL -o livv.sh \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/livv.sh

    echo -e "[\e[1;35m*\e[0m] Installing .gitignore..."
    test -f .gitignore || \
        curl -sL -o .gitignore \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/livv/.gitignore

    chmod +x ansible.sh livv.sh

    echo -e "[\e[1;35m*\e[0m] Running composer install..."
    composer install 1> /dev/null 2> /dev/null
    
    echo -e "[\e[1;35m*\e[0m] Running artisan tasks..."
    php artisan migrate:fresh --seed --force -q
    php artisan key:generate --force -q
    php artisan storage:link --force -q

    echo -e "[\e[1;35m*\e[0m] Running pnpm install..."
    pnpm install 1> /dev/null 2> /dev/null 
}

nonexistent() {
    composer create-project laravel/laravel "$PROJECT"
    cd "$PROJECT"
    pnpm dlx @preset/cli apply laravel:inertia
    existent
}

while [[ ${1} ]]; do
    case "${1}" in
        -n|--project|-p)
            PROJECT=${2}
        ;;
        --launch|-l)
            LAUNCH="true"
        ;;
        --no-launch|-nl)
            LAUNCH="false"
        ;;
        --upgrade|-u)
            UPGRADE="true"
        ;;
        --no-upgrade|-nu)
            UPGRADE="false"
        ;;
        --help|-h)
            help
        ;;
        --version|-v)
            version
        ;;
        *)
            PROJECT=${1}
        ;;
    esac

    shift
done

[ -f $PROJECT/artisan ] && existent || nonexistent
[ "$UPGRADE" == "true" ] && upgrade
[ "$LAUNCH" == "true" ] && launch