#!/usr/bin/env bash
#
# Arquivo: sf-laravel
# Descrição: Scaffolding Laravel
#
# Mais um script feito com ❤️ por: 
# - "Lucas Saliés Brum" <lucas@archlinux.com.br>
# 
# Criado em: 23/09/2021 01:33:12
# Atualizado: 30/09/2022 12:07:24
#
# Referência:
# FG: reset = 0, black = 30, red = 31, green = 32, yellow = 33, blue = 34, magenta = 35, cyan = 36, white = 37
# BG: reset = 0, black = 40, red = 41, green = 42, yellow = 43, blue = 44, magenta = 45, cyan = 46, white=47

PROJECT="$(pwd)/laravel"
TMUX_SESSION="Laravel"
LAUNCH="false"
BROWSER="firefox"

[ $1 ] && PROJECT=$1
[ ! -e $PROJECT ] && composer create-project laravel/laravel $PROJECT

cd $PROJECT

test -f database/database.sqlite || touch database/database.sqlite
test -d .vscode || mkdir .vscode
test -d .github/workflows || mkdir -p .github/workflows

# .gitignore
test -f .gitignore || \
    curl -sL -o .gitignore \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/common/gitignore

# VSCode Settings
test -f .vscode/settings.json || \
    curl -sL -o .vscode/settings.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/common/settings.json

# VSCode Tasks
test -f .vscode/tasks.json || \
    curl -sL -o .vscode/tasks.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/laravel/tasks.json

# Github Workflows
test -f .github/workflows/laravel.yml || \
    curl -sL -o .github/workflows/laravel.yml \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/laravel/laravel.yml

# Laravel .env
test -f .env || \
    read -p "Substituir o arquivo .env? [s/N]: " substituir
    
    [ "$substituir" == *[sS]* ] && \    
    curl -sL -o .env \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/laravel/.env

# Laravel .env.example
test -f .env.example && \
    read -p "Substituir o arquivo .env.example? [s/N]: " substituir

    [ "$substituir" == *[sS]* ] && \
        curl -sL -o .env.example \
        https://raw.githubusercontent.com/sistematico/sf-scripts/main/laravel/.env.example

php artisan migrate:fresh --seed --force
php artisan key:generate
php artisan storage:link

if [ "$LAUNCH" == "true" ]; then
    \tmux has-session -t $TMUX_SESSION 2>/dev/null
    if [ $? != 0 ]; then
        \tmux kill-session -t $TMUX_SESSION
    fi

    \tmux new-session -d -s $TMUX_SESSION
        
    \tmux new-window -t $TMUX_SESSION -n artisan -d

    \tmux send-keys -t $TMUX_SESSION:artisan "cd $PROJECT ; pnpm run dev ; php artisan serve" ENTER

    \tmux detach -s $TMUX_SESSION
fi

if [ "$LAUNCH" == "true" ]; then
    $BROWSER http://localhost:8000
    \tmux attach -t $TMUX_SESSION
fi