#!/usr/bin/env bash
#
# Vite.js Scaffolding
#
# Criado em 06/11/2021 01:37:11
# Atualizado em 06/11/2021 01:38:50
#
# FG: reset = 0, black = 30, red = 31, green = 32, yellow = 33, blue = 34, magenta = 35, cyan = 36, white = 37
# BG: reset = 0, black = 40, red = 41, green = 42, yellow = 43, blue = 44, magenta = 45, cyan = 46, white=47

[ ! -d .github/workflows ] && mkdir -p .github/workflows
[ ! -d .vscode ] && mkdir -p .vscode

test -f .vscode/tasks.json || \
    curl -sL -o .vscode/tasks.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/vscode/tasks.json

test -f .vscode/settings.json || \
    curl -sL -o .vscode/settings.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/common/settings.json

test -f .github/workflows/ci.yml || \
    curl -sL -o .github/workflows/ci.yml \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/common/gh-actions/pages.yml