#!/usr/bin/env bash
#
# Arquivo: sf-vite
# Descrição: Vite.js Scaffolding
#
# Mais um script feito com ❤️ por: 
# - "Lucas Saliés Brum" <lucas@archlinux.com.br>
# 
# Criado em: 23/09/2021 01:33:12
# Atualizado: 20/05/2022 17:46:51

[ $1 ] && PROJECT="$1" || PROJECT="vitejs"
BROWSER="firefox"
LAUNCH="true"
TMUX_SESSION="Vite"

[ ! -d $PROJECT ] && pnpm create vite $PROJECT -- --template vue-ts

cd $PROJECT

test -d .vscode || mkdir .vscode
test -d .github/workflows || mkdir -p .github/workflows

# .gitignore
test -f .gitignore || \
    curl -sLo .gitignore \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/vitejs/gitignore

# VSCode Settings
test -f .vscode/settings.json || \
    curl -sLo .vscode/settings.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/common/settings.json

# VSCode Recommendations
test -f .vscode/extensions.json || \
    curl -sLo .vscode/extensions.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/vitejs/extensions.json

# VSCode Tasks
test -f .vscode/tasks.json || \
    curl -sLo .vscode/tasks.json \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/vitejs/tasks.json

# Github Workflows
test -f .github/workflows/vite.yml || \
    curl -sLo .github/workflows/vite.yml \
    https://raw.githubusercontent.com/sistematico/sf-scripts/main/vitejs/vite.yml

pnpm install 1> /dev/null

if [ "$LAUNCH" == "true" ]; then
    \tmux has-session -t $TMUX_SESSION
    [ $? != 0 ] && \tmux kill-session -t $TMUX_SESSION
    \tmux new-session -d -s $TMUX_SESSION 2> /dev/null
    \tmux new-window -t $TMUX_SESSION -n pnpm -d
    \tmux send-keys -t $TMUX_SESSION:pnpm "cd $PROJECT ; pnpm run dev" ENTER
    \tmux detach -s $TMUX_SESSION
fi

[ "$LAUNCH" == "true" ] && $BROWSER http://localhost:3000